
spring.datasource.url=jdbc:postgresql://localhost:5432/escondida
spring.datasource.username=${DATABASE_USE:postgres}
spring.datasource.password=${DATABASE_PASSWORD:postgres}
app.token=${APP_TOKEN:defaultSecretKeyForCIOnlyDoNotUseInProduction1234567890}


spring.datasource.driver-class-name=org.postgresql.Driver
server.port=8081
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.main.allow-circular-references=true